version: '2.1'

services:
  db:
    image: mariadb:10.1.23
    volumes:
      - ./config/mysql:/etc/mysql/conf.d

  gems:
    image: busybox
    volumes:
      - /ruby_gems

  redis:
    image: redis:3.2.9
    sysctls:
      - net.core.somaxconn=65535

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app

  selenium_hub:
    image: selenium/hub

  selenium_chrome:
    image: selenium/node-chrome

  selenium_chrome_debug:
    image: selenium/node-chrome-debug

  selenium_chrome_standalone:
    image: selenium/standalone-chrome

  selenium_chrome_standalone_debug:
    image: selenium/standalone-chrome-debug
