version: '2.1'

services:
  db:
    extends:
      file: docker-compose-common.yml
      service: db
    container_name: rth_db_production
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=rth_production
      - MYSQL_PASSWORD=Ex@7W809!!
      - MYSQL_DATABASE=rth_production

  gems:
    extends:
      file: docker-compose-common.yml
      service: gems
    container_name: rth_gems_production

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    container_name: rth_redis_production

  sidekiq:
    extends:
      file: docker-compose-common.yml
      service: sidekiq
    container_name: rth_sidekiq_production
    depends_on:
      - db
      - gems
      - redis
    volumes_from:
      - gems
    environment:
      - RAILS_ENV=production
    entrypoint: ./docker-entrypoint.sh
    command: ["sidekiq", "-C", "config/sidekiq.yml"]

  api:
    extends:
      file: docker-compose-common.yml
      service: api
    container_name: rth_api_production
    depends_on:
      - db
      # - elasticsearch
      - gems
      - sidekiq
    volumes_from:
      - gems
    ports:
      - 3301:3000
    environment:
      - RAILS_ENV=production
    entrypoint: ./docker-entrypoint.sh
    command: ["rails", "server", "-b0"]
