version: '2.1'

services:
  db:
    extends:
      file: docker-compose-common.yml
      service: db
    container_name: rth_db_pre_production
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pwd@888
      - MYSQL_DATABASE=rth_pre_production

  gems:
    extends:
      file: docker-compose-common.yml
      service: gems
    container_name: rth_gems_pre_production

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis
    container_name: rth_redis_pre_production

  sidekiq:
    extends:
      file: docker-compose-common.yml
      service: sidekiq
    container_name: rth_sidekiq_pre_production
    depends_on:
      - db
      - gems
      - redis
    volumes_from:
      - gems
    environment:
      - RAILS_ENV=pre_production
    entrypoint: ./docker-entrypoint.sh
    command: ["sidekiq", "-C", "config/sidekiq.yml"]

  api:
    extends:
      file: docker-compose-common.yml
      service: api
    container_name: rth_api_pre_production
    depends_on:
      - db
      - gems
      - sidekiq
    volumes_from:
      - gems
    ports:
      - 3201:3000
    environment:
      - RAILS_ENV=pre_production
    entrypoint: ./docker-entrypoint.sh
    command: ["rails", "server", "-b0"]
