default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV['RAILS_MAX_THREADS'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: rth_development

test: &test
  <<: *default
  database: rth_test

staging:
  <<: *default

pre_production:
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
